name: Create Release

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_KEYSTORE_PATH: ${{ secrets.RELEASE_KEYSTORE_PATH }}
      RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
      RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Checkout metadata
        uses: actions/checkout@v2
        with:
          repository: hash-checker/metadata
          token: ${{ secrets.ACCESS_TOKEN }}
          path: './metadata'

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: caches-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Release Bundle
        run: ./gradlew bundleRelease --stacktrace

      - name: Build Release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.head_commit.message }}
          release_name: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Upload Release Bundle with Google Play services
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 'app/build/outputs/bundle/googlePlayRelease/hash-checker_release.aab'
          asset_name: hash-checker_google-play_${{ github.event.head_commit.message }}.aab
          asset_content_type: application/zip

      - name: Upload Release Bundle without Google Play services
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 'app/build/outputs/bundle/thirdPartyStoresRelease/hash-checker_release.aab'
          asset_name: hash-checker_no-google-play_${{ github.event.head_commit.message }}.aab
          asset_content_type: application/zip

      - name: Upload Release APK with Google Play services
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 'app/build/outputs/apk/googlePlay/release/hash-checker_release.apk'
          asset_name: hash-checker_google-play_${{ github.event.head_commit.message }}.apk
          asset_content_type: application/zip

      - name: Upload Release APK without Google Play services
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 'app/build/outputs/apk/thirdPartyStores/release/hash-checker_release.apk'
          asset_name: hash-checker_no-google-play_${{ github.event.head_commit.message }}.apk
          asset_content_type: application/zip
